---
- name: build process on ansible slave
  hosts: all
  become: true
  tasks:
    - name: install dependencies 
      apt:
        name:
          - openjdk-17-jdk
          - maven
          - git
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"
